### ISSUE TITLE
codename: simplify

### ISSUE THREAD

**Issue by alberanid** [alberanid/imdbpy#61]
IMDbPY contains a lot of legacy code and needs some new features.
Let's fix it in the master branch. :-)

If you need the old version (supporting Python 2.7), look at the *imdbpy-legacy* branch.

- [x] remove the "mobile" parser
- [x] remove SQLObject support
- [x] remove the cutils C module (keep it, but make it optional and off by default)
- [x] move to Python 3: #27 
  - [x] http parser
  - [x] sql parser
- [x] introduce support for the new data set: #60 
- [ ] introduce python-requests for queries (to support sessions): #87 
- [x] introduce documentation about those changes

Optionally:
- [x] remove the BeautifulSoup dependency (python-lxml will be required)
- [ ] if possible, re-introduce Python 2.7 compatibility

**Comment by alberanid** [comment]
Closing it, since the bulk of the work is done.

python-requests needs too much dependencies.
